CUDA_VISIBLE_DEVICES=0 python main.py \
    --data_root ./ \
    --train_data_path ../adaface_org/AdaFace/data/faces_emore/imgs_subset \
    --val_data_path data/DL23_Dataset \
    --test_data_path data/faces_webface_112x112 \
    --prefix irse50_coseface \
    --use_wandb \
    --gpus 1 \
    --use_16bit \
    --arch ir_se_50 \
    --batch_size 218 \
    --num_workers 16 \
    --epochs 28\
    --lr_milestones 12,20,24 \
    --lr 0.1 \
    --head cosface \
    --m 0.4\
    --distributed_backend ddp \
    --low_res_augmentation_prob 0.2 \
    --crop_augmentation_prob 0.0 \
    --photometric_augmentation_prob 0.2\
    --custom_num_class 52158\