CUDA_VISIBLE_DEVICES=0 python main.py \
    --data_root ./ \
    --train_data_path ../webface_subset \
    --val_data_path data/DL23_Dataset \
    --test_data_path data/faces_webface_112x112 \
    --prefix ir50_adaface_cls \
    --use_wandb \
    --gpus 1 \
    --use_16bit \
    --arch ir_50 \
    --batch_size 128 \
    --num_workers 16 \
    --epochs 30\
    --lr_milestones 8,16,24 \
    --lr 0.1 \
    --head adaface \
    --m 0.4 \
    --h 0.333 \
    --s 64.0 \
    --t_alpha 0.1\
    --distributed_backend ddp \
    --low_res_augmentation_prob 0.2 \
    --crop_augmentation_prob 0.2 \
    --photometric_augmentation_prob 0.2\
    --custom_num_class 3980\